name: publish-technical-documentation-k6

on:
  push:
    branches:
      - main
    paths:
      - "docs/sources/k6/**"
  workflow_dispatch:
jobs:
  sync:
    if: github.repository == 'grafana/k6-docs'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: grafana/writers-toolkit/publish-technical-documentation@c4c701f5bf349638f9a56ff5368471329d696fd0
        with:
          source_directory: docs/sources/k6
          website_directory: content/docs/k6
