name: Update `make docs` procedure
on:
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main:
    if: github.repository == 'grafana/k6-docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: grafana/writers-toolkit/update-make-docs@f65819d6a412b752c0e0263375215f049507b0e6
        with:
          pr_options: >
            --label type/docs
          trace: true
